openshift/cluster-operator

- cmd/cluster-operator-controller-manager/app/controllermanager.go
The wait that was being done in controller-manager only checked that the main api server was healthy. We need to wait until the cluster-operator api server has registered its api extensions.
Fixes #2.
> Move discovery of server resources into retry loop so that controller-manager maits for extension registration on start-up

- README.md
- contrib/examples/deploy.yaml
- pkg/ansible/generate.go
- pkg/ansible/generate_test.go
- pkg/ansible/runner.go
- pkg/controller/infra/infra_controller.go
Currently blocked on error where no boto3/botocore is available in the container. Will be submitting a PR tomorrow to openshift-ansible and possibly building my own container to bypass.
Open for review none the less.
> provision cluster infra with openshift-ansible

- cmd/cluster-operator-controller-manager/app/controllermanager.go
Wait for the cluster-operator.openshift.io resource group to be registered with the aggregation API server prior to starting controllers.
> Delay starting controllers

- pkg/controller/infra/infra_controller.go
- pkg/controller/jobcontrol.go
- pkg/controller/jobcontrol_test.go
This will remove boilerplate code that needs to be copied to all of the individual controllers that are using a jobcontrol.
> Move job event handling to jobcontrol from individual controllers

- cmd/cluster-operator-controller-manager/app/controllermanager.go
- contrib/examples/cluster.yaml
- contrib/examples/create-cluster.sh
- contrib/examples/deploy.yaml
- pkg/ansible/generate.go
- pkg/ansible/generate_test.go
- pkg/ansible/jobgenerator.go
- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/clusteroperator/zz_generated.deepcopy.go
- pkg/controller/client_utils.go
- pkg/controller/controller_utils.go
- pkg/controller/infra/infra_controller.go
- pkg/controller/machineset/machineset_controller.go
- pkg/openapi/openapi_generated.go
- pkg/registry/clusteroperator/cluster/strategy.go
- pkg/registry/clusteroperator/machineset/strategy.go
Updates machineset controller to run the appropriate provisioning playbooks
> Machineset controller

- pkg/controller/jobcontrol.go
This is not resilient to errors that happen when deleting the configmap. If the delete fails, it will not be retried (unless deleting the job failed as well).
> Delete configmaps after deleting the associated jobs

- pkg/apis/clusteroperator/validation/machineset.go
- pkg/apis/clusteroperator/validation/machineset_test.go
> Allow controlling owner of machineset to be non-first owner

- pkg/controller/cluster/cluster_controller_test.go
> Add tests for cluster controller around changes to the hardware specs

- pkg/ansible/generate.go
Adds the containerized=True variable to the variables passed to ansible playbooks.
> Perform containerized installation of master

- cmd/cluster-operator-controller-manager/app/controllermanager.go
- cmd/cluster-operator-controller-manager/app/options/options.go
- pkg/ansible/generate.go
- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/clusteroperator/zz_generated.deepcopy.go
- pkg/apis/componentconfig/types.go
- pkg/controller/components/components_controller.go
- pkg/openapi/openapi_generated.go
Adds a controller to install components on a cluster that has accepted compute/infra nodes.
> Add controller to install components on master

- pkg/ansible/generate.go
deploying to anything other than us-east-1 means we need to provide our own vpc/subnet details as openshift-ansible/roles/openshift_aws only provides details for us-east-1.
provide some defaults for us-east-1, us-east-2, us-west-1, and us-west-2
> add default vpc settings

- pkg/controller/infra/infra_controller.go
call new infra uninstaller that mirrors existing playbooks/cluster-operator/infrastructure.yml provisioning
this requires latest openshift-ansible
> use new infra uninstaller

- contrib/examples/cluster.yaml
- pkg/controller/machineset/machineset_controller.go
Updates the playbook called for machineset deprovisioning
Also updates the ami used in the sample cluster
> Hookup deprovisioning playbook

- test/integration/controller_test.go
> Fix data race in integration test

- pkg/controller/cluster/cluster_controller.go
if a DeletionTimestamp is set on a cluster, it ensures that all MachineSets belonging to that cluster get deleted (or already have a DeletionTimestamp).
> Delete machinesets in cluster controller

- pkg/ansible/jobgenerator.go
- pkg/ansible/jobgenerator_test.go
- pkg/controller/components/components_controller.go
Requires https://github.com/openshift/openshift-ansible/pull/7473.
Time to install from clean: ~12 minutes.
> Run each components playbook in parallel in a separate container

- README.md
- cmd/cluster-operator-apiserver/app/testing/server_test.go
- contrib/ansible/deploy-devel.yaml
- contrib/apiserver-aggregation-tls-setup.sh
- contrib/examples/cluster.yaml
- contrib/examples/create-cluster.sh
- contrib/examples/deploy.yaml
- contrib/examples/get-playbook-mock-runs.sh
- contrib/fake-openshift-ansible/fake-openshift-ansible
- pkg/apis/clusteroperator/validation/cluster_test.go
- pkg/apis/clusteroperator/validation/machineset_test.go
- pkg/registry/clusteroperator/cluster/storage_test.go
Put global cluster-operator resources in the openshift-cluster-operator namespace instead of the cluster-operator namespace.
> Use openshift-cluster-operator as the namespace

- Makefile
- build/apiserver-builder/Dockerfile
- build/clusterapi-image/Dockerfile
Initial target to build cluster api container image locally
To build image:
```
make kubernetes-cluster-api
```
> Add target for upstream cluster API image

- .gitignore
Ignore local cluster.yaml in the form of $(whoami)-cluster.yaml
> Ignore customized local cluster yaml

- Makefile
- cmd/aws-machine-controller/machine-controller.go
- contrib/cmd/aws-actuator-test/main.go
- pkg/clusterapi/aws/actuator.go
Adds an AWS machine controller to use with cluster API
> AWS machine controller for cluster API

- Makefile
- build/aws-machine-controller/Dockerfile
- build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api.yaml
- build/cluster-operator-ansible/playbooks/cluster-api-prep/files/cluster-api-template.yaml
Adds a make target to build the aws-machine-controller image
Modifies the cluster-api deployment playbook to include the aws-machine-controller
> Machine controller deployment

- contrib/cmd/cluster-api-export/export.go
Adds a command that creates Cluster API resources based on an existing cluster operator Cluster and MachineSets
> Export cluster API resources

- pkg/ansible/generate.go
Adds inventory variable to enable auto-approve of nodes
> Enable auto approval of node CSRs

- build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api.yaml
- build/cluster-operator-ansible/playbooks/cluster-api-prep/files/cluster-api-template.yaml
- pkg/clusterapi/aws/actuator.go
Fix to some issues found during testing of the cluster API with the aws-machine-controller. Also adds additional debugging.
> Fix AWS actuator, double-encoding of bootstrap kubeconfig

- contrib/examples/create-cluster.sh
Uses env var CLUSTER_NAME if present
> Allow specifying a cluster name

- pkg/ansible/generate.go
Set a default number of docker registry replicas
> Set number of docker registry replicas

- README.md
> README updates for Mac

- Makefile
Updates the build target to use the new cluster-api repository.
> Update make build target for kubernetes-cluster-api image

- pkg/controller/client_utils.go
More work pulled from https://github.com/dgoodwin/cluster-operator/commits/cluster-api.
> Provide function for patch cluster-api Cluster status

- README.md
Look right @csrwng ? Seems to be working for me, and super handy.
> Document how to run controllers locally for development productivity.

- cmd/cluster-operator-controller-manager/app/controllermanager.go
- pkg/controller/client_builder.go
Includes cluster api resources when getting available resources
> Check availability of cluster API resources

- Makefile
- contrib/examples/clusterapi-template.yml
- pkg/clusterapi/aws/actuator.go
Still not quite there, but closer. Details in commits.
> Small changes working towards AWS actuator working on master.

- pkg/clusterapi/aws/actuator.go
Our Ansible currently dynamically looks up the masters via searching for
instances with certain tags. Modified the actuator to add these tags to match 
generate.go.
> Fix AWS actuator to tag instances as required.

- cmd/cluster-operator-apiserver/app/testing/server_test.go
- cmd/cluster-operator-controller-manager/app/controllermanager.go
- cmd/cluster-operator-controller-manager/app/options/options.go
- contrib/examples/cluster-deployment-template.yaml
- contrib/examples/clusterapi-template.yml
- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/apis/clusteroperator/validation/clusterdeployment.go
- pkg/apis/clusteroperator/validation/clusterdeployment_test.go
- pkg/apis/componentconfig/types.go
- pkg/clusterapi/aws/actuator.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/controller/combinedcluster.go
- pkg/controller/controller_utils.go
- pkg/controller/controller_utils_test.go
- pkg/controller/infra/infra_controller_test.go
- pkg/registry/clusteroperator/clusterdeployment/storage_test.go
Watches cluster deployments and creates a cluster-api cluster and master machineset for each
> ClusterDeployment controller

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
A change in size of the master machineset config inside a clusterdeployment was not resulting in a change in replicas of the cluster API master machineset.
> Fix update of machineset replicas on clusterdeployment sync

- cmd/cluster-operator-controller-manager/app/controllermanager.go
- cmd/cluster-operator-controller-manager/app/options/options.go
- pkg/apis/componentconfig/types.go
- pkg/controller/controller_utils.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
resurect syncmachineset controller to watch ClusterDeployment and Cluster objects and sync Cluster and non-master machinesets to remote cluster
> machine set / cluster syncing controller

- build/cluster-operator-ansible/playbooks/cluster-operator/aws/infrastructure.yml
- pkg/ansible/generate.go
I've smooshed vars for infra, master and compute in order to pass all groups to the infra playbook for iam role creation.
> Create master and node iam roles within the infrastructure playbook.

- README.md
> Update README.md to include more setup information

- contrib/cmd/wait-for-cluster-ready/waitforcluster.go
Modifies wait-for-cluster-ready to only wait until the ClusterAPI is installed on the target cluster. 
It also introduces a timeout flag to quit when a timeout expires.
> Update wait-for-cluster-ready command

- contrib/cmd/wait-for-cluster-ready/waitforcluster.go
Add a polling wait for the cluster to be created in the wait-for-cluster-ready utility. This is needed when invoking the utility right after creating the clusterdeployment. It needs to allow the clusterdeployment controller to create the cluster first.
> Wait for cluster to be created when waiting for it to be ready

- test/integration/controller_test.go
Through all the refactors the integration tests ended up hardcoding a
lot of logic at a lower level than they need to. (manually creating
clusters and machine sets)
Instead move up one level and create a cluster deployment, and let this
create the expected machine sets and cluster.
> Stop bypassing cluster deployments in integration tests.

- pkg/ansible/generate.go
- pkg/ansible/generate_test.go
- pkg/ansible/jobgeneratorexecutor.go
- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/defaults.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/apis/clusteroperator/validation/clusterdeployment.go
- pkg/apis/clusteroperator/validation/clusterdeployment_test.go
- pkg/openapi/openapi_generated.go
- pkg/registry/clusteroperator/clusterdeployment/storage_test.go
Required, immutable, and defaulted to match openshift-ansible.
> Hook up SDN plugin name.

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Specifies a duration to be added to creation time, after which the
cluster deployment is considered expired and should be cleaned up.
Cluster deployments will be requeued for one minute after this time to
ensure timely cleanup.
> Add support for cluster delete-after annotation.

- Makefile
- build/cluster-operator-ansible/Dockerfile
- build/test-image/Dockerfile
- contrib/cmd/wait-for-cluster-ready/waitforcluster.go
- contrib/pkg/cluster/waitforcluster.go
- test/integration/controller_test.go
Fixes issues with verify tests not passing.
Adds a 'test-image' to be used when running verification and unit tests
> Changes related to getting on ci-operator

- contrib/cmd/coutil/main.go
- contrib/pkg/amibuild/command.go
- contrib/pkg/amibuild/generate.go
- contrib/pkg/amibuild/run.go
- contrib/pkg/amiid/getid.go
Adds a utility command to build an AMI given an RPM Repository URL
> Utility to build AMI

- build/cluster-operator/Dockerfile
> Add coutil binary to cluster operator image

- build/cluster-operator-ansible/playbooks/cluster-operator/aws/install_masters.yml
Workaround for the removal in https://github.com/openshift/openshift-ansible/pull/9680
> Set openshift_master_cluster_hostname as internal elb hostname.

- Makefile
> Add coutil verify-import to make verify.

- Makefile
- build/build-image/Dockerfile
- contrib/ansible/deploy-devel-playbook.yml
- contrib/pkg/provision_aws/command.go
- contrib/pkg/provision_aws/generate.go
> Fix image problems
