- Makefile
- pkg/registry/clusteroperator/cluster/strategy_test.go
- pkg/registry/clusteroperator/node/strategy_test.go
- pkg/registry/clusteroperator/nodegroup/strategy_test.go
* Default to building natively instead of using docker containers. Set USE_DOCKER=1 to build inside docker container. Replaces NO_DOCKER=1 to build natively.
* Fix bugs in registry strategy tests so that they verify that Cluster, NodeGroup, and Node are namespace-scoped.
* Disable integration tests in CI until integration tests are set up properly.
> Resolve outstanding issues related to jenkins CI

- contrib/apiserver-aggregation-tls-setup.sh
- contrib/examples/deploy.sh
tell bash to not continue if any commands return non-zero
update 'oc create namespace' since that errors when the namespace already exists
> don't continue on errors

- cmd/cluster-operator-controller-manager/app/controllermanager.go
Node group controller was using "nodeGroups" instead of "nodegroups" for the name of the resource that *needed* to exist.
> Use the correct name for the nodegroups resource so that the nodegroup controller isn't skipped

- cmd/cluster-operator-apiserver/app/server.go
- cmd/cluster-operator-apiserver/app/testing/server_test.go
- cmd/cluster-operator-controller-manager/app/controllermanager.go
- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
- pkg/apis/clusteroperator/validation/cluster.go
- pkg/apis/clusteroperator/validation/cluster_test.go
- pkg/apis/clusteroperator/validation/node.go
- pkg/apis/clusteroperator/validation/node_test.go
- pkg/apis/clusteroperator/validation/nodegroup.go
- pkg/apis/clusteroperator/validation/nodegroup_test.go
- pkg/apis/clusteroperator/validation/validation.go
- pkg/apis/clusteroperator/validation/validation_test.go
- pkg/controller/cluster/cluster_controller.go
- pkg/controller/controller_utils.go
- pkg/openapi/openapi_generated.go
* Add validation for the API resources.
* Remove NodeGroupName from Node as it is not currently used. It may not be needed at all depending upon how we implement nodes. So, let's get rid of it for now.
* Fix some fmt and lint warnings.
> Add validation for the API resources.

- contrib/ansible/deploy-devel.yaml
default the cluster-operator install playbook to continue to use 'default', but allow passing cli_aws_section to pick a different aws profile to run with/against
> allow using non 'default' aws profile names

- contrib/hack/coverage.sh
- contrib/hack/utilities.sh
* Coverage analysis is done by running `make coverage`. This produces an HTML file at cluster-operator/coverage.html where you can see covered and uncovered code in each file.
* Currently, analysis is only run on packages that contain tests. The scripts are written exit out on the first package encountered without a test. There are two things we can do about this in the future. First, once we have at least some tests in all packages, we can adjust the scripts to run the coverage analysis on all packages, and we can treat packages without tests as a failure. Second, we can adjust the scripts so that they handle packages without tests as code with 0% coverage instead of as a failure.
> Add scripts for running test coverage analysis

- contrib/examples/deploy.yaml
- pkg/ansible/generate.go
- pkg/ansible/runner.go
- pkg/controller/infra/infra_controller.go
Also adds support for creating clusters in namespaces other than
"cluster-operator".
For now, secrets we use for AWS and SSH are copied to any namespace where a cluster appears. These will fold into the cluster API and/or provisioning eventually.
Ansible jobs will also run in the namespace where the cluster lands keeping things nicely segmented.
> Allow running Ansible without root/elevated SCC.

- .gitignore
- Makefile
- README.md
- build/fake-openshift-ansible/Dockerfile
- cmd/cluster-operator-controller-manager/app/controllermanager.go
- cmd/cluster-operator-controller-manager/app/options/options.go
- contrib/ansible/deploy-devel.yaml
- contrib/examples/deploy.yaml
- contrib/fake-openshift-ansible/fake-openshift-ansible
- pkg/ansible/runner.go
- pkg/apis/componentconfig/types.go
- pkg/controller/infra/infra_controller.go
* `make images` will now also build a fake-openshift-ansible image built on top of the openshift/origin-ansible image. This new image will not actually execute the playbook. All it does now is validate that certain environment variables are set and files exist. Eventually, the playbook will do more validation and log playbooks run to a server for further validation.
* The ansible image to use is configurable in controller-manager via command-line arguments.
* contrib/ansible/deploy-devel.yaml has been modified to allow the user to use either the fake image or connect to the real AWS. If the `use_real_aws` variable is set to true when running the playbook, then the real openshift-ansible image will be used, which connects to the real AWS.
* The echo command has been removed from …
> Provide a fake openshift-ansible image to avoid real AWS

- README.md
- contrib/examples/cluster.yaml
- contrib/examples/create-cluster.sh
To avoid having to copy over the cluster.yaml file when using the real AWS, I created a template for creating clusters where the cluster name can be specified as a template parameter. I also created a script to use for creating a cluster that will default to creating a cluster whose name is prefaced with the user name. So, by default, if a cluster is created with the creation script, then the cluster will be named appropriately for use in AWS.
> Use username in cluster creation by default

- Makefile
- build/playbook-mock/Dockerfile
- contrib/ansible/deploy-devel.yaml
- contrib/cmd/playbook-mock/main.go
- contrib/examples/deploy-playbook-mock.yaml
- contrib/examples/get-playbook-mock-runs.sh
- contrib/fake-openshift-ansible/fake-openshift-ansible
- contrib/pkg/playbookmock/server.go
- glide.lock
- vendor/github.com/gorilla/context/.travis.yml
- vendor/github.com/gorilla/context/LICENSE
- vendor/github.com/gorilla/context/README.md
- vendor/github.com/gorilla/context/context.go
- vendor/github.com/gorilla/context/context_test.go
- vendor/github.com/gorilla/context/doc.go
- vendor/github.com/gorilla/mux/.travis.yml
- vendor/github.com/gorilla/mux/LICENSE
- vendor/github.com/gorilla/mux/README.md
- vendor/github.com/gorilla/mux/bench_test.go
- vendor/github.com/gorilla/mux/context_gorilla.go
- vendor/github.com/gorilla/mux/context_gorilla_test.go
- vendor/github.com/gorilla/mux/context_native.go
- vendor/github.com/gorilla/mux/context_native_test.go
- vendor/github.com/gorilla/mux/doc.go
- vendor/github.com/gorilla/mux/mux.go
- vendor/github.com/gorilla/mux/mux_test.go
- vendor/github.com/gorilla/mux/old_test.go
- vendor/github.com/gorilla/mux/regexp.go
- vendor/github.com/gorilla/mux/route.go
* Create a playbook-mock server. This will be deployed as part of the cluster-operator deploy unless the `use_real_aws=true` variable is given to the ansible playbook.
* Update the fake-openshift-ansible script to log the playbook being run with the playbook-mock server.
* Create a script at contrib/examples/get-playbook-mock-runs.sh that will display the playbook runs that have been logged with the playbook-mock server.
The calls made to the playbook-mock server can be seen in a number of ways.
1) Look at the logs in the playbook-mock server.
`oc logs -n cluster-operator $(oc get pods -n cluster-operator -l app=playbook-mock -o json | jq -r .items[0].metadata.name)`
2) Call the http server of the playbook-mock server using the service name
`curl …
> Create server to capture ansible playbooks run by fake-openshift-ansible

- pkg/ansible/jobgenerator.go
- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
- pkg/controller/cluster/cluster_controller.go
- pkg/controller/infra/infra_controller.go
- pkg/controller/jobcontrol.go
- pkg/controller/jobcontrol_test.go
- pkg/controller/master/master_controller.go
- pkg/openapi/openapi_generated.go
`JobControl` can be re-used by other controllers (master, machineset) that need to start jobs to do work.
> Create type for handling jobs for controllers

- contrib/ansible/deploy-devel.yaml
This change hasn't yet appeared in the v3.9 tag so latest will have to
do for now.
> Use latest tag for origin-ansible which now contains boto deps.

- pkg/controller/infra/infra_controller.go
Call combined cluster-operator infrastructure playbook in place of openshift-ansible AWS prerequisites playbook.
playbooks/cluster-operator/aws/infrastructure.yml is responsible for creating:
* VPC
* SSH keypair
* security groups
* S3 bucket (added)
* ELB (added)
> Swap prerequisites playbook for CO infrastructure playbook

- build/fake-openshift-ansible/Dockerfile
- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/controller/infra/infra_controller.go
- pkg/registry/clusteroperator/cluster/strategy.go
Add some handling in syncCluster() for when a cluster object has been marked for deletion
Fire off a non-JobControl(ed) job to run the 'uninstall_prerequisites.yml' playbook to remove the infra pieces
Update from the origin-ansible:v3.8 to 'latest' since that's where the uninstall/deprovision playbooks exist.
> cluster infra delete/deprovision

- pkg/controller/client_utils.go
- pkg/controller/cluster/cluster_controller.go
- pkg/controller/cluster/cluster_controller_test.go
* If patch is an empty JSON object, then do not send the patch request.
* Use a patch with retries to update the cluster from `cluster.Controller`.
Fixes #59.
> Do not send patch requests for objects that have not had any changes

- pkg/ansible/generate.go
Remove API and console port overrides. https://github.com/openshift/openshift-ansible/pull/6889 breaks overriding and removes the need to override the ports for the time being.
> Remove API and console port overrides.

- cmd/cluster-operator-apiserver/app/server.go
- pkg/apiserver/config.go
- pkg/apiserver/etcd_config.go
The integration tests will start and stop API Servers. This will keep those tests from leaking go routines.
> Clean up etcd stores on API Server shutdown

- cmd/cluster-operator-controller-manager/app/controllermanager.go
- pkg/ansible/jobgenerator.go
- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/clusteroperator/zz_generated.deepcopy.go
- pkg/controller/client_utils.go
- pkg/controller/cluster/cluster_controller.go
- pkg/controller/controller_utils.go
- pkg/controller/infra/infra_controller.go
- pkg/controller/infra/infra_controller_test.go
- pkg/controller/jobcontrol.go
- pkg/controller/jobcontrol_test.go
- pkg/controller/jobsync.go
- pkg/controller/machine/machine_controller.go
- pkg/controller/machineset/machineset_controller.go
- pkg/controller/master/master_controller.go
- pkg/openapi/openapi_generated.go
**Changes**
* Implement the controller that is responsible for installing openshift on the master nodes.
* Create a JobSync type to pull together more of the duplicated code around syncing for controllers that rely on jobs.
* Increase the duration that ansible jobs can run before failing. This is needed now because the machines created in AWS are not available for a while after the scale groups are created. The machineset job that creates the scale groups completes successfully prior to the machines in the scale groups being accessible. The pods of the master job will fail until the master machines are accessible. We wanted to increase this duration anyway, so now is as good a time as any.
**Notes**
* The latest docker.io/openshift/origin-ansible does not work with cluster-operator. …
> Implement master controller

- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/controller/cluster/cluster_controller.go
- pkg/controller/controller_utils.go
- pkg/controller/controller_utils_test.go
- pkg/controller/jobcontrol.go
* Adds unit tests for the functions in pkg/controller/controller_utils.go.
* Replaces all occurrences where code gets a controlling owner for an object with calls to a new `GetObjectController` function. The existing `ClusterForMachineSet` now calls this new function.
Fixes #61.
> Unit tests for controller_utils.go

- contrib/examples/cluster.yaml
- pkg/ansible/generate.go
- pkg/controller/machineset/machineset_controller.go
- pkg/controller/master/master_controller.go
When we get more parameterization on the openshift-ansible side we'll be able to get rid of the complex structs that we're passing in vars. But for now, these changes make provisioning work, up to the point where we have a master and nodes running. The last remaining step is to approve the nodes.
> Tweaks to make ec2 provisioning work

- Makefile
- build/build-image/Dockerfile
The build machine does not have all of the tools that `make verify` uses. To get around this, I've re-enabled using a docker image for builds.
> Use docker for builds and tests

- pkg/ansible/generate.go
- pkg/ansible/generate_test.go
Generate vars for a single compute group, instead of naming them after the machineset.
For now, multiple compute machinesets are not supported by the openshift-ansible playbooks (nodes will not be able to autojoin the cluster). This makes it so that we use the fixed "compute" group for compute machinesets. It means that for any given cluster you can only have a single compute machineset for now. Support for multiple machinesets will need to first be done on the openshift-ansible side.
> Use single compute label for compute nodes

- cmd/cluster-operator-controller-manager/app/controllermanager.go
- cmd/cluster-operator-controller-manager/app/options/options.go
- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/clusteroperator/zz_generated.deepcopy.go
- pkg/apis/componentconfig/types.go
- pkg/controller/accept/accept_controller.go
- pkg/controller/controller_utils.go
- pkg/controller/infra/infra_controller.go
- pkg/controller/master/master_controller.go
- pkg/openapi/openapi_generated.go
Adds a new controller to run to the accept playbook for a cluster where all machinesets have been provisioned and the master machineset is installed.
> Controller to accept nodes in cluster master

- contrib/examples/cluster.yaml
- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
- pkg/apis/clusteroperator/validation/clusterversion.go
- pkg/apis/clusteroperator/validation/clusterversion_test.go
- pkg/openapi/openapi_generated.go
- pkg/registry/clusteroperator/clusterversion/storage_test.go
- test/integration/clustercontroller_test.go
Rename OpenshiftVersion to just Version to better accomodate possiblity
of installing base Kubernetes in the future.
Version will at worst, look something like "v3.9.0-alpha.4+e7d9503-18"
and at best, something like "v3.9.0". We may add validation on this
format once it's content is more solidified.
> Move deployment type and version from cluster config to version.

- pkg/controller/cluster/cluster_controller.go
- pkg/controller/cluster/cluster_controller_test.go
Modifies cluster controller to ignore size when deciding whether to recreate a machineset due to a spec change.
Updates unit tests to use instance type instead of size to test machineset mutation.
> Allow machineset scaling

- cmd/cluster-operator-controller-manager/app/controllermanager.go
- pkg/ansible/generate.go
- pkg/ansible/generate_test.go
- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/clusteroperator/zz_generated.deepcopy.go
- pkg/controller/accept/accept_controller.go
- pkg/controller/cluster/cluster_controller.go
- pkg/controller/machineset/machineset_controller.go
- pkg/controller/master/master_controller.go
- pkg/openapi/openapi_generated.go
- test/integration/controller_test.go
* Each controller runs its playbook without worrying about whether other playbooks that set up dependencies have been run yet. If those dependencies are have not been set up yet, then the dependent playbook will fail and be retried. This greatly simplifies the controllers because they do not have to worry about checking on the state into which other controllers have put the kube objects.
* A MachineSet object contains all of the information that is needed to run playbooks for the MachineSet. Controllers syncing a MachineSet no longer need to fetch the owning Cluster.
In my experience, running all the ansible playbooks in parallel has actually slowed the total time that it takes to go from cold start to a working cluster. This may be due to the exponential backoffs of the jobs making it so …
> Run all playbook jobs in parallel

- contrib/examples/cluster.yaml
- pkg/ansible/generate.go
- pkg/ansible/generate_test.go
- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/defaults.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
- pkg/openapi/openapi_generated.go
This is added to sit along-side the SSHKey.
Today this setting is largely dependent on the AMI and we require the
user to exist already.
Long term this setting will probably die, being replaced by global
cluster operator configuration for a user that we will ensure is created
on every host via the upcoming config DaemonSet work from kwoodson.
For now this gives us flexibility to adjust per cluster as ami's come
and go.
> Add SSHUser to cluster hardware info.

- Makefile
- build/update-apiserver-gen.sh
This is work product that comes out of trying to resolve the issue of the thrashing in the openapi_generated.go file. The root of that issue is still not known entirely to me. It happens when you have an openapi-gen executable that was built outside of docker that you are using inside of docker to generated the openapi files. The workaround is to delete bin/openapi-gen when moving between building out of and in docker. This PR will let the CI catch generated openapi files that use the incorrect version.
> Verify generated files as part of make verify

- pkg/ansible/generate.go
This change will cause masters to configure cloudprovider credentials in `/etc/sysconfig/...` files. We might want to separate provisioning credentials from cloudprovider credentials eventually... this just piggy backs on the credentials we have.
> Add cloudprovider configuration which references AWS credentials via job environment.

- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/controller/accept/accept_controller.go
- pkg/controller/cluster/cluster_controller.go
- pkg/controller/components/components_controller.go
- pkg/controller/infra/infra_controller.go
- pkg/controller/jobcontrol.go
- pkg/controller/jobsync.go
- pkg/controller/jobsync_test.go
- pkg/controller/jobsyncstrategy.go
- pkg/controller/machineset/machineset_controller.go
- pkg/controller/master/master_controller.go
- pkg/controller/mockjobcontrol_generated_test.go
- pkg/controller/mockjobsyncstrategy_generated_test.go
- test/integration/controller_test.go
- test/integration/jobutils.go
- test/integration/waitutils.go
When a cluster or a machine set is deleted, a job is created to deprovision. The cluster or machine set is blocked from being fully deleted until the playbook completes successfully. Note that if the job fails, then the user will have to manually delete the cluster or machine set by removing the appropriate finalizer. This gives the user an opportunity to see that there was a failure and do any manual deprovisioning needed.
By default, when a cluster is deleted, the machine sets that it owns are deleted as well, since the owner reference on the machine set for the cluster has the `blockDeletion` field set to true.
There is not *yet* a playbook to deprovision the machine set. Consequently, a job to deprovision a machine set will never succeed, and a machine set will never be fully deleted …
> Deprovision clusters and machine sets

- pkg/ansible/jobgenerator.go
- pkg/controller/jobcontrol.go
- pkg/controller/jobsync.go
- pkg/controller/jobsync_test.go
The job controller uses longer and longer delays as the pods of a job fail. For the compute provision jobs, there can be large delays, in excess of 5 minutes, between when a pod completes successfully and when a job is updated to have a completed status. For clust-op controllers that wait for other jobs to complete before starting their jobs, this can significantly increase the time that it takes to stand up a cluster.
As part of a circumvention to this problem, this PR limits the number of failures for our jobs to 3 and re-creates the job when that limit is reached. As future work, it would be good to also (1) include some backoff wait between job failure and job creation and (2) stop the job re-creation after a sufficiently long time of failures.
Note: In the interest of avoiding a …
> Circumvent long delays in job completion after pod success

- contrib/ansible/deploy-devel.yaml
- contrib/examples/create-cluster.sh
add ability to use something besides hardcoded libra.pem ssh key filename
use $(whoami)-cluster.yaml as cluster definition if file exists
> allow providing custom ssh key and custom cluster definition

- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/clusteroperator/zz_generated.deepcopy.go
- pkg/controller/accept/accept_controller.go
- pkg/controller/components/components_controller.go
- pkg/controller/infra/infra_controller.go
- pkg/controller/jobcontrol.go
- pkg/controller/jobcontrol_test.go
- pkg/controller/jobsync.go
- pkg/controller/jobsync_test.go
- pkg/controller/jobsyncstrategy.go
- pkg/controller/machineset/machineset_controller.go
- pkg/controller/master/master_controller.go
- pkg/controller/mockjobcontrol_generated_test.go
- pkg/controller/mockjobsyncstrategy_generated_test.go
- pkg/openapi/openapi_generated.go
- test/integration/jobutils.go
- test/integration/waitutils.go
Modifies job sync and job control to keep retrying when a job fails. 
The job generation field in the cluster and machineset status structs now only gets a value if a job has completed successfully for a given generation.
> Restart jobs when they fail

- contrib/ansible/deploy-devel.yaml
deployment will fail in non-obvious ways later, so just detect and bail out if we see a password protected ssh key trying to be used
> trying to use a password-protected ssh key isn't supported

- contrib/ansible/deploy-devel.yaml
Logic was wrong for when the libra.pem is not encrypted, task would fail
when we actually want it to continue.
> Fix deploy when libra.pem not pass protected.

- README.md
- cmd/cluster-operator-controller-manager/app/controllermanager.go
- cmd/cluster-operator-controller-manager/app/options/options.go
- contrib/ansible/deploy-devel.yaml
- contrib/examples/cluster.yaml
- contrib/examples/create-cluster.sh
- contrib/examples/deploy.yaml
- pkg/ansible/image.go
- pkg/ansible/image_test.go
- pkg/ansible/jobgenerator.go
- pkg/ansible/jobgenerator_test.go
- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/clusteroperator/validation/clusterversion.go
- pkg/apis/clusteroperator/validation/clusterversion_test.go
- pkg/apis/clusteroperator/zz_generated.deepcopy.go
- pkg/apis/componentconfig/types.go
- pkg/controller/accept/accept_controller.go
- pkg/controller/components/components_controller.go
- pkg/controller/infra/infra_controller.go
- pkg/controller/infra/infra_controller_test.go
- pkg/controller/machineset/machineset_controller.go
- pkg/controller/master/master_controller.go
- pkg/controller/mockjobcontrol_generated_test.go
- pkg/openapi/openapi_generated.go
- test/integration/controller_test.go
* Removes the ansible image command-line arguments to controller-manager. The controllers will determine the ansible image to use based on the information in the ClusterVersion resource. The default is "openshift/origin-ansible:{TAG}", where {TAG} is `ClusterVersion.Spec.Version`. The default is overridden by specifying a value for `ClusterVersion.Spec.OpenshiftAnsibleImage`. The default pull policy is IfNotPresent. The default pull policy is overridden by specifying a value for `ClusterVersion.Spec.OpenshiftAnsibleImagePullPolicy`.
* Removes the `use_real_aws` parameter from the ansible deployment playbook. This is replaced with a `USE_REAL_AWS` variable in the create cluster script. Additionally, the ansible image and pull policy can be specified explicitly by setting the …
> Use an openshift-ansible image appropriate for a ClusterVersion

- contrib/examples/cluster.yaml
More commonly used for development, and seems to work fine for our purposes.
> Switch to t2.medium for test cluster.

- contrib/examples/cluster.yaml
- contrib/examples/create-cluster.sh
Latest now picks up 3.10 changes which break, possibly because we're
trying to use them against AMIs with 3.9.
> Default to origin-ansible v3.9 instead of latest.

- cmd/cluster-operator-apiserver/app/testing/server_test.go
- contrib/examples/cluster.yaml
- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
- pkg/apis/clusteroperator/validation/cluster.go
- pkg/apis/clusteroperator/validation/cluster_test.go
- pkg/controller/accept/accept_controller.go
- pkg/controller/cluster/cluster_controller.go
- pkg/controller/cluster/cluster_controller_test.go
- pkg/controller/components/components_controller.go
- pkg/controller/controller_utils.go
- pkg/controller/controller_utils_test.go
- pkg/controller/infra/infra_controller.go
- pkg/controller/infra/infra_controller_test.go
- pkg/controller/jobcontrol.go
- pkg/controller/jobcontrol_test.go
- pkg/controller/jobsync.go
- pkg/controller/jobsync_test.go
- pkg/controller/machineset/machineset_controller.go
- pkg/controller/master/master_controller.go
- pkg/openapi/openapi_generated.go
- pkg/registry/clusteroperator/cluster/storage_test.go
- test/integration/controller_test.go
- test/integration/jobutils.go
* MachineSets will have the following labels.
- `cluster-uid` matching the UID of the owning cluster
- `cluster` matching the name of the owning cluster
- `machine-set-short-name` matching the short name from the cluster spec for the machine set
* Jobs and Configmaps will have the following labels.
- `cluster-uid` or `machine-set-uid` matching the UID of the owning resource
- `cluster` or `machine-set` matching the name of the owning resource
- `job-type` type of the job (e.g., "provision", "infra", "accept")
- if owning resource is a machine set, then all of the labels from the owning machine set
* For example, a components job will have the following labels.
- `cluster-uid`: uid of the cluster
- `cluster`: name of the cluster
- `machine-set-uid`: uid of the master machine set
- …
> Add labels for owner relationships

- Makefile
- build/cluster-operator-ansible/Dockerfile
- build/cluster-operator-ansible/cluster-api-prep/deploy-cluster-api.yaml
- build/cluster-operator-ansible/cluster-api-prep/files/cluster-api-template.yaml
new ansible automation to deploy cluster-api images onto a cluster (based on template from https://github.com/kubernetes/kube-deploy/blob/master/cluster-api/cloud/google/config/configtemplate.go )
lay additional ansible files on top of openshift-ansible at playbooks/cluster-api-prep/deploy-cluster-api.yaml
provide the following ansible variables for deployment:
cluster_api_image: location of container image to pull/run (default quay.io/openshift/kubernets-cluster-api:latest)
it will generate a certificate, or you can provide your own:
cluster_api_ca_bundle: CA bundle for cluster-api services
cluster_api_cert: certificate for services
cluster_api_key: key for services
> cluster-api installer

- cmd/cluster-operator-controller-manager/app/controllermanager.go
- cmd/cluster-operator-controller-manager/app/options/options.go
- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/clusteroperator/zz_generated.deepcopy.go
- pkg/apis/componentconfig/types.go
- pkg/controller/deployclusterapi/deployclusterapi_controller.go
- pkg/controller/jobcontrol_test.go
- pkg/openapi/openapi_generated.go
Still need to address a bug where the playbook keeps recreation the controllers each run but this should be operational for now.
> Add a controller to periodically deploy the kube cluster API controllers.

- build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api.yaml
oc_process template has a particular way of determining whether an object in a template already exists on the cluster. just use 'oc process | oc apply' instead of the oc_process module.
this should keep the pods from restarting whenever the cluster-api installation is re-run, since 'oc apply' will know not to modify the already existing 'Deployment' objects.
> idempotentize cluster-api-template

- contrib/examples/deploy.yaml
- pkg/ansible/jobgenerator.go
- pkg/controller/master/master_controller.go
update clusterrole permissions to allow creating/querying serviceaccounts and rolebindings
add steps to master_controller to create a serviceaccount that can create secrets (to eventually hold a target cluster's kubeconfig)
update jobgenerator to allow specifying a serviceaccount that should be attached to the pod/job
> Secret creation serviceaccount

- contrib/examples/cluster.yaml
We're really struggling with performance and stability on t2.medium.
> Bump test cluster instance type to t2.xlarge.

- contrib/ansible/deploy-devel.yaml
- contrib/examples/deploy.yaml
If either the apiserver or cluster cert secrets do not exist, generate a
new local set of certs, and store as secrets.
etcd in the cluster itself will serve as the shared storage for these
across the team for a deployment.
> Generate certs if secrets do not exist.

- contrib/ansible/deploy-devel.yaml
- contrib/examples/deploy.yaml
- pkg/ansible/jobgenerator.go
This is not actually used in the template, rather an assumed set of
credentials we use in the job generator. (will probably eventually
be configmap driven)
Renamed the secret keys to work around a bug in the k8s_raw module.
> Extract AWS creds secret from template.

- contrib/examples/deploy.yaml
Cluster data will now persist across deleting the apiserver pod.
> Add a PersistentVolumeClaim for our apiserver etcd instance.

- Makefile
- build/fake-openshift-ansible/Dockerfile
Right now the fake-ansible image run if you don't specify to USE_REAL_AWS is failing for any job that runs one of our custom playbooks, the only thing this container does is verify the playbook exists, which it wouldn't as it was based off origin-ansible.
Reordered image build to follow the cluster-operator-ansible image, and assumed we can safely build off canary if we're building this image. (as it wouldn't be a part of any official build)
> Fix fake-ansible image missing our playbooks.

- contrib/examples/deploy.yaml
Deploying didn't work for me because the pvc got created in the current namespace instead of the cluster-operator-namespace
> Create etcd pvc in cluster operator namespace

- pkg/ansible/generate.go
I'd prefer the env vars to be a parameter to the `oc_adm_router` module but this is how we would add env vars today.
> Override openshift_hosted_router_edits to enable ROUTER_USE_PROXY_PROTOCOL.

- build/cluster-operator-ansible/playbooks/cluster-operator/aws/install_masters.yml
Before creating the kubeconfig secret, set the current context in the kubeconfig to the one that will allow external access.
> Set the current context of the cluster kubeconfig to the external one

- Makefile
- contrib/examples/cluster.yaml
- contrib/examples/create-cluster.sh
change target cluster-operator-ansible-images to build cluster-operator-ansible images that can be used to install 3.9 and 3.10 OpenShift clusters (still allow building canary/custom).
get cluster-creation to use new versioned c-o-a images
> building various cluster-operator-ansible images

- README.md
- contrib/ansible/create-cluster-playbook.yaml
- contrib/ansible/deploy-devel-playbook.yml
- contrib/ansible/deploy-playbook.yaml
These commits switch us from using shell commands / k8s_raw to my in-progress kubectl_apply and oc_process wrapper modules. Per discussion last week we're going to use our deployment Ansible as a testbed for these and see where they go. The path back to k8s_raw once it's more production ready should be quite straightforward.
With this change Ansible 2.5 is no longer required.
The roles are vendored using another tool I wrote (gogitit), but this is only relevant to the person doing the vendoring. None the less the metadata files are available if anyone else needed to do this, and the README is updated with details on how.
> Kubectl apply module

- pkg/ansible/generate.go
- pkg/ansible/generate_test.go
- pkg/controller/components/components_controller.go
provide the number of infra nodes when generating ansible variables so that we can do things like set the number of replicas for some components based on that size.
as a temporary measure, keep registy replicas hardcoded to 1 for now while we wait for a move to S3-backed storage as running more than 1 registry with non-shared storage (separate PVs in the current setup) will result in problems
update tests so that we have clusters with a machineset having infra: true
> set registry count to the number of infra nodes (max 2)

- Dockerfile
- Makefile
- README.md
- contrib/ansible/create-cluster-playbook.yaml
- contrib/ansible/deploy-devel-playbook.yml
- contrib/ansible/deploy-playbook.yaml
- contrib/examples/cluster-operator-roles-template.yaml
- contrib/examples/cluster-operator-template.yaml
Deploying will now create a BuildConfig, ImageStream, and
DeploymentConfig. However until you push images there's nothing for the
DeploymentConfig to run.
You can push images in two ways, either start-build to build the latest
git master, or a make target to push your locally built images.
(development)
May want to actually test this one.
> Convert to builds, image streams and deployment configs.

- build/cluster-operator-ansible/playbooks/cluster-api-prep/files/cluster-api-template.yaml
- contrib/cmd/cluster-api-export/export.go
The latest version of the cluster API controller manager doesn't take a --cloud flag anymore.
A valid cluster API cluster now requires some network settings. For export command, these are populated with dummy values.
> Fixes to cluster-api deployment and export

- contrib/cmd/aws-actuator-test/main.go
- pkg/clusterapi/aws/actuator.go
On successful AWS instance delete, updates the machine resource to remove the finalizer. This allows the machine resource to go away.
Follows pattern in upstream GCP actuator:
https://github.com/kubernetes-sigs/cluster-api/blob/029f15be7c227663cdd99f80ec4bca499b66ae57/cloud/google/machineactuator.go#L387-L388
> AWS actuator: remove finalizer on successful delete

- contrib/ansible/create-cluster-playbook.yml
- contrib/examples/cluster-template.yaml
This is needed to use an alternate keypair for CI
> Parameterize AWS SSH keypair name

- cmd/cluster-operator-controller-manager/app/controllermanager.go
- pkg/controller/client_builder.go
This is needed for cluster-api controllers that will be added.
This was authored by @dgoodwin as part of https://github.com/dgoodwin/cluster-operator/commit/36cb76ebb3a48dbe90aca0b54d3c2ccbd88ba987.
> Start a cluster-api informer in controller manager

- cmd/cluster-operator-controller-manager/app/controllermanager.go
This will be used by controller-manager when deciding whether to start the new cluster-api controllers that will be added.
> Add check that controller-manager can use to verify that cluster-api resources are available

- cmd/cluster-operator-controller-manager/app/controllermanager.go
- contrib/examples/cluster-operator-roles-template.yaml
* Start the shared informers for the cluster-api in controller-manager.
* Give controller-manager user full permissions to the cluster-api resources.
> Start cluster-api informers in controller-manager

- contrib/cmd/extract-co-jenkins-logs/main.go
- contrib/cmd/extract-co-jenkins-logs/util/dockerinfo.go
- contrib/cmd/extract-co-jenkins-logs/util/download.go
- contrib/cmd/extract-co-jenkins-logs/util/extractlogs.go
Adds command that will extract container logs from a given Jenkins job. It will create a separate file for each container log either in the current directory or a directory specified by `--output-dir`
> Add utility to extract e2e test container logs

- pkg/apiserver/etcd_config.go
Fix the dump way that I built the RESTOptions for cluster-api.
> Stop wrapping RESTOptions for cluster-api unneccessarily

- contrib/ansible/create-cluster-playbook.yml
- contrib/ansible/deploy-devel-playbook.yml
Due to the order in which things merged, master currently will stall on
a devel deployment waiting for it to complete, when we expect you to
make a decision on how to get images. (make push-integrated registry, or
oc start-build)
With this change devel deployments now assume to run make images, and
make integrated-registry-push, then wait for the deployment to roll out.
You no longer need to choose a deployment method.
This makes a devel deployment playbook run much slower, but this should
not be part of normal workflow, typically you just run make images push
yourself, or run your controller externally when working.
With this change creation of the default cluster versions can move back
to it's more logical location.
> Fix infinitely stalled devel deployment.

- Makefile
- build/cluster-operator/Dockerfile
- contrib/examples/cluster-api-controllers-template.yaml
Previously was using an image from quay.io, meaning we couldn't make
local changes and run them in the root cluster. Now bundles the actuator
with our main cluster operator image, and uses the same ImageStream our
other deployment configs use.
> Deploy AWS actuator from source in root CO cluster.

- pkg/apis/clusterapi/validation/machine.go
- pkg/apis/clusterapi/validation/validation.go
- pkg/apiserver/etcd_config.go
This is not super clean as supplementing the validation is not something that the apiserver-builder is designed to support. Nevertheless, it works without too much trouble.
* Adds sample validation to Machine that can be removed once some real validation of any of the cluster-api resources has been added.
> Provide a means for adding custom validation

- README.md
noticed it was needed while setting up a new machine to run cluster-operator locally
> document need for python2-libselinux

- pkg/ansible/generate.go
Switches to using global names for IAM roles instead of names suffixed with the cluster ID
> Use global IAM role names

- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/clusteroperator/zz_generated.deepcopy.go
- pkg/openapi/openapi_generated.go
The original reason for this is so we can specify which images to use in CI. However, it also makes sense that we track these images per version.
> Add cluster API and machine controller image refs to ClusterVersion

- build/clusterapi-image/Dockerfile
When the cluster-api image is built in CI, the binaries don't get the executable permission. Ensure that the binaries are executable.
> Ensure cluster API binaries are executable in image

- pkg/clusterapi/aws/actuator.go
- pkg/controller/clusterapimachine/machine_controller.go
- pkg/controller/controller_utils.go
With this change the control plane masters will now be created for a new
cluster API. Their machineset will need to manually be deleted for time
being.
Fixes an error in logs where we were double deleting the finalizer now
that upstream implemented it as well.
> Use AWS credentials for actuator EC2 client when defined.

- build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api.yaml
- build/cluster-operator-ansible/playbooks/cluster-api-prep/files/cluster-api-template.yaml
- contrib/ansible/deploy-devel-playbook.yml
- contrib/examples/cluster-versions-template.yaml
- pkg/ansible/generate.go
Allows passing variables to the deploy-cluster-api playbook to point to alternate images for the machine controller and cluster-api.
For now, the default location of these images will be the registry on api.ci where we'll update the latest tag every time we merge to master.
For PRs we will push to the same registry with a pr-specific tag and tell the target cluster to use that.
> Parameterize images to deploy on target cluster

- cmd/cluster-operator-controller-manager/app/controllermanager.go
- pkg/ansible/generate.go
- pkg/ansible/generate_test.go
- pkg/ansible/jobgeneratorexecutor.go
- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/controller/client_utils.go
- pkg/controller/clusterapimachine/machine_controller.go
- pkg/controller/clusterinstall/controller.go
- pkg/controller/components/components_controller.go
- pkg/controller/controller_utils.go
- pkg/controller/infra/infra_controller.go
- pkg/controller/infra/infra_controller_test.go
- pkg/controller/jobsync.go
- pkg/controller/jobsync_test.go
- pkg/controller/syncmachineset/syncmachineset_controller.go
- pkg/controller/syncmachineset/syncmachineset_controller_test.go
- test/integration/controller_test.go
- test/integration/jobutils.go
- test/integration/waitutils.go
* Added integration tests using the cluster-api resources.
* Fixed flake where integration tests were occasionally failing due to missing deprovision job. See https://trello.com/c/cdGM9KVt.
* Use UPDATE to update cluster status since we cannot do a strategic merge of the ProviderStatus.
* Fixed a number of bugs with capi controllers.
* Moved cluster name label used on MachineSets to a common location.
> Integration tests using CAPI

- Makefile
- build/generate-mocks.sh
Fail CI when the generated mocks are not up-to-date, built with the latest version of gomock and mockgen.
> Verify that generated mocks are up-to-date

- pkg/controller/components/components_controller.go
- pkg/controller/controller_utils.go
- pkg/controller/infra/infra_controller.go
- pkg/controller/infra/infra_controller_test.go
- test/integration/controller_test.go
This was set up to look for a infra capi.MachineSet to get the size,
however we do not create this in the root cluster, so the infra job was
not spawning.
Instead it should use the co.Cluster.Spec.MachineSets just as we did
previously.
> Fix infra controller lookup of infra machineset size.

- contrib/ansible/deploy-playbook.yml
- contrib/examples/cluster-api-controllers-template.yaml
- contrib/examples/cluster-operator-roles-template.yaml
- contrib/examples/cluster-operator-template.yaml
These changes were required to get deployed in our CI cluster.
Handle scenario where namespace is pre-existing and we do not have perms
to create it ourselves.
Fixed missing namespace on auth template.
Removed use of image pull policy "never" which we should not need.
> Additional fixes for prod like deployments.

- contrib/examples/clusterapi-template.yml
In the absence of the now delete machine controller, manually setup the
provider config. This just allows testing until the flip to generate
everything off a ClusterDeployment is ready.
Fixes case on the Master role to match the upstream constant, which was
causing control plane install jobs not to trigger as it couldn't find a
master machine set.
> Fix clusterapi template master role and provider config.

- contrib/ansible/deploy-playbook.yml
- contrib/examples/cluster-api-controllers-template.yaml
Root cluster was still deploying the old quay.io image, this should match what was done for the target cluster recently.
> Update image for cluster API controllers in root cluster.

- Makefile
Common to have temporary files, logs, and patches laying around
a git repo, verify-mocks was refusing to run despite these files not
being tracked by git.
Switch to a more forgiving method of checking for local changes.
> Fix verify-mocks refusing to run due to untracked files.

- pkg/controller/infra/infra_controller.go
These machinesets are not currently being created and nothing sets this
required status boolean as a result. As such capi.Clusters cannot be
deleted right now, as they are blocked by the infra deprovision
finalizer which never gets removed.
Until we are creating remote machinesets again this check should just
return true.
> Temporarily allow infra deprovision without deleting remote machinesets.

- Makefile
- cmd/cluster-operator-controller-manager/app/controllermanager.go
- cmd/cluster-operator-controller-manager/app/options/options.go
- pkg/apis/componentconfig/types.go
- pkg/clusterapi/aws/actuator.go
- pkg/clusterapi/aws/utils.go
- pkg/clusterapi/aws/utils_test.go
- pkg/controller/awselb/aws_elb_controller.go
- test/integration/controller_test.go
Watches machines, and if they're masters adds them to internal/external ELB. This happens on every machine sync, the API call appears idempotent, however if we feel this is too much chatter I could modify to only re-try adding to the ELB after a certain amount of time has elapsed since successfully being added.
Also disables the check for deprovisioning remote machinesets as we do not
currently create them, and this blocks the infra deprovision job and
thus cluster deletion.
> Add controller to add masters to internal/external ELB.

- Makefile
- README.md
- build/fake-machine-controller/Dockerfile
- cmd/fake-machine-controller/machine-controller.go
- contrib/ansible/create-cluster-playbook.yml
- contrib/ansible/deploy-devel-playbook.yml
- contrib/ansible/deploy-playbook.yml
- contrib/examples/cluster-api-controllers-template.yaml
- contrib/examples/cluster-versions-template.yaml
- pkg/clusterapi/fake/actuator.go
Adds a fake machine controller and introduces a variable that can be set on deployment to either use real or fake images.
Whether you use a real or fake cluster now depends on the `use_real_images` variable passed to the deploy-devel-playbook and not on which cluster_version is used to create the cluster.
> Create a fake cluster operator environment by default

- pkg/clusterapi/aws/actuator.go
- pkg/clusterapi/aws/utils.go
I failed to manually test after PR refactoring from review, this was
leftover from when we were using a sorted array with the newest instance
first, and even then it looks like it might have been a bug.
> Fix delete machine bug.

- pkg/controller/jobcontrol.go
- pkg/controller/jobcontrol_test.go
- pkg/controller/jobsync.go
- pkg/controller/jobsync_test.go
- pkg/controller/mockjobcontrol_generated_test.go
Undo jobs will have "undo" in their names. For example, the undo infra job will have a name like `infra-undo-test-cluster-6r9tl`.
> Include "undo" in the name of undo jobs

- pkg/controller/controller_utils.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
Also use clusterID as a prefix to remote machineset names. Using clusterID for the cluster will be done in a separate pull.
> Remove AWS credentials before syncing cluster/machinesets

- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/controller_utils.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
> Change cluster name from clusterDeployment.Name to clusterDeployment.Spec.ClusterID

- build/cluster-operator-ansible/playbooks/cluster-operator/aws/infrastructure.yml
For now, skips role creation on infra until we get back to per-cluster roles.
> Skip role creation on infra

- contrib/examples/cluster-api-controllers-template.yaml
Removed based on https://github.com/kubernetes-sigs/cluster-api/blob/master/cloud/google/config/configtemplate.go#L120-L123.
```
$ oc logs cluster-api-controller-manager-859b5894f-c6m6b -n openshift-cluster-operator
unknown flag: --incluster
Usage of ./controller-manager:
--kubeconfig string                      Path to kubeconfig file with authorization and master location information.
--leader-elect                           Start a leader election client and gain leadership before executing the main loop. Enable this when running replicated components for high availability.
--leader-elect-lease-duration duration   The duration that non-leader candidates will wait after observing a leadership renewal until attempting to acquire leadership of a led but unrenewed leader slot. This is …
```
> Remove --incluster from cluster-api-controller-manager command.

- .gitignore
- pkg/clusterapi/aws/actuator.go
- pkg/clusterapi/aws/actuator_test.go
> Change node instances to 'terminate' by default.

- contrib/cmd/aws-actuator-test/main.go
> Fix aws-actuator-test

- .gitignore
- contrib/cmd/aws-actuator-test/main.go
- pkg/clusterapi/aws/actuator.go
- pkg/clusterapi/aws/actuator_test.go
- pkg/clusterapi/aws/utils.go
>  Detect and terminate stopped nodes

- contrib/ansible/deploy-devel-playbook.yml
We likely don't need to rebuild images every time we deploy. This introduces a separate flag so we can control whether images should be built but still allow pushing them to the internal registry.
> Introduce separate flag to build images on deployment

- cmd/cluster-operator/controller-manager.go
- cmd/cluster-operator/main.go
some environments build go binaries as 'debug' before launching the debugger. gracefully handle the posibility that controller-manager will be launched as 'debug'.
> handle running controller-manager in debug session

- contrib/examples/cluster-versions-template.yaml
- contrib/examples/clusterapi-template.yml
- pkg/clusterapi/aws/actuator.go
- pkg/clusterapi/aws/actuator_test.go
This will need to be updated on our side once https://github.com/openshift/openshift-ansible/pull/8923 is backported to 3.10 and we've created a new AMI using the updated release-3.10 branch.
> Set openshift_node_config_name in userdata.

- Makefile
- pkg/clusterapi/aws/actuator.go
Uses the latest 3.10 latest commit from openshift-ansible. Until we get a tag in that branch, we will just pull the latest.
Also modifies the actuator to add a `openshift-node-group-config` tag to the instance
> Use latest ansible 3.10 branch

- contrib/ansible/deploy-devel-playbook.yml
Skips trying to process the clusterversion template if a clusterversion already exists.
> Skip cluster version template if clusterversion exists

- build/cluster-operator-ansible/Dockerfile
release-3.10 has been branched for openshift-ansible so we should use it in the cluster-operator-ansible build.
> Use release-3.10 branch instead of master for cluster-operator-ansible build.

- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
- pkg/openapi/openapi_generated.go
Fixes issue when clusterdeployment never gets to sync remote machinesets and gets deleted, the finalizer for the remote machinesets remains and doesn't allow the clusterdeployment to be deleted.
> Skip remote machineset cleanup when sync never happend

- contrib/ansible/deploy-devel-playbook.yml
The reason the existence check is failing is because the ServiceUnavailable error is not the only error returned when the apiserver is not ready yet. So now just testing for either of the possible valid outcomes ... either there is no error or the error contains "NotFound". Otherwise, keep retrying.
> Fix check for clusterversion existence

- contrib/examples/cluster-deployment-template.yaml
- pkg/ansible/generate.go
- pkg/ansible/generate_test.go
- pkg/ansible/jobgeneratorexecutor.go
- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/defaults.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/clusteroperator/validation/clusterdeployment.go
- pkg/apis/clusteroperator/validation/clusterdeployment_test.go
- pkg/apis/clusteroperator/zz_generated.deepcopy.go
- pkg/controller/controller_utils.go
- pkg/openapi/openapi_generated.go
- pkg/registry/clusteroperator/clusterdeployment/storage_test.go
Re-use the cluster-api NetworkConfig struct.
Supports multiple ranges but currently validates that only one is
provided, as this appears to be all openshift-ansible supports.
Will default if none is provided.
Once set these values are immutable.
> Hookup pod and service network CIDRs in the API.

- Makefile
- contrib/ansible/deploy-devel-playbook.yml
- contrib/cmd/wait-for-apiservice/waitforservice.go
- Adds utility that waits until the API service is working and available.
- Updates the makefile to include utility binary builds in the image target
- Updates the deployment playbook so that it uses the new utility to ensure the clusteroperator apiservice is available.
> Utility to wait for existence and ready status of an API service

- contrib/examples/cluster-deployment-template.yaml
Restores default values to CIDR for services and pods in template.
> Fix cluster deployment template subnets

- contrib/cmd/aws-actuator-test/main.go
- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
- pkg/clusterapi/aws/actuator.go
- pkg/clusterapi/aws/actuator_test.go
- pkg/clusterapi/aws/utils.go
- pkg/controller/awselb/aws_elb_controller.go
- pkg/controller/awselb/aws_elb_controller_test.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/controller_utils.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
- pkg/openapi/openapi_generated.go
> Remove ClusterID field from MachineSetSpec

- Makefile
- build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api.yaml
- build/cluster-operator-ansible/playbooks/cluster-api-prep/files/.gitignore
- build/cluster-operator-ansible/playbooks/cluster-api-prep/files/cluster-api-template.yaml
When testing/developing on AWS actuator, we have to go through the trouble of pushing an image to an external registry and manually changing the deployment on the target cluster. Also when CI tests it, we're not really testing the built AWS actuator on the target cluster. This pull does the following:
- Add the aws-machine-controller binary to the cluster-operator-ansible image
- Modifies the playbook that deploys the cluster api to copy the aws-machine-controller binary to the target master
- Modifies the template for the cluster-api to do a host mount for the aws-machine-controller binary so that it uses that instead of whatever was on the image.
This results in the following limitations:
- Only 1 master is supported
- Only the aws-machine-controller binary is copied over. Other changes …
> Use aws-machine-controller binary on target cluster

- Makefile
- build/cluster-operator-ansible/playbooks/cluster-api-prep/.gitignore
- build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api-common.yaml
- build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api-development.yaml
- build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api-production.yaml
- build/cluster-operator-ansible/playbooks/cluster-api-prep/files/cluster-api-template.yaml
- build/cluster-operator-ansible/playbooks/cluster-api-prep/files/machine-controller-template-dev.yaml
- build/cluster-operator-ansible/playbooks/cluster-api-prep/files/machine-controller-template.yaml
- contrib/ansible/deploy-devel-playbook.yml
Creates a separate cluster-operator-ansible image that supports the binary mount of aws-machine-controller. That way, if you want to use the normal non-hacky way of running aws-machine-controller, you can specify the original image when deploying cluster-operator:
```
./contrib/ansible/deploy-devel-playbook.yml -e ansible_image=cluster-operator-ansible:canary
```
The default will be to use the new :dev tag so that we get our code onto the target cluster.
It also includes the fix to copy the machine controller binary to all masters, enabling support for > 1 master.
> Mount aws-machine-controller binary only in development case

- pkg/controller/controller_utils.go
- pkg/controller/controller_utils_test.go
While reviewing another PR, I noticed that there were a handful of unused labels consts in controller_utils.go. This PR removes those. It also removes the unneeded "cluster-uid" label and replaces the "cluster" label placed on jobs with the more specific and ubiquitous "clusteroperator.openshift.io/cluster" label.
> Remove unused label consts.

- contrib/ansible/create-cluster-playbook.yml
- contrib/examples/cluster-deployment-template.yaml
- pkg/ansible/generate.go
- pkg/ansible/jobgenerator.go
> Add public ssh key to cluster create

- build/cluster-operator-ansible/Dockerfile
- build/cluster-operator-ansible/roles/openshift_aws/tasks/security_group.yml
- pkg/ansible/generate.go
- pkg/clusterapi/aws/actuator.go
Currently we ignore VPCName from the hardware spec. This PR makes it so we honor it and assume it exists when set. We also need a fix in the ansible openshift_aws role to use the vpc name instead of assuming it's the cluster name. That is getting fixed here: https://github.com/openshift/openshift-ansible/pull/9249
When that fix goes through and it gets backported to 3.10, we can remove the override in this repo.
> Honor VPC name and Subnet in AWS hardware spec

- build/cluster-operator-ansible/Dockerfile
- build/cluster-operator-ansible/run
- contrib/fake-openshift-ansible/fake-openshift-ansible
- pkg/ansible/generate.go
- pkg/ansible/jobgenerator.go
using '-e' with ansible-playbook means that the variables included with the '-e' are immutable.
migrate the format of the vars file to be an ansible inventory file that applies to '[all]' hosts to avoid this immutability.
use INVENTORY_DIR when running the openshift-ansible container (instead of INVENTORY_FILE) to pull in the hosts and vars files in /ansible/inventory/.
fix handing of INVENTORY_DIR in openshift-ansible when the files are symlinks (it would copy the symlink instead of the contents of what the symlinks were pointing to). https://github.com/openshift/openshift-ansible/pull/9309 is the upstream fix.
> stop including ansible vars with '-e'

- cmd/cluster-operator-apiserver/app/testing/server_test.go
- contrib/ansible/create-cluster-playbook.yml
- contrib/examples/cluster-deployment-template.yaml
- pkg/ansible/generate.go
- pkg/ansible/generate_test.go
- pkg/registry/clusteroperator/clusterdeployment/storage_test.go
- pkg/registry/clusteroperator/clusterdeployment/strategy.go
- pkg/registry/clusteroperator/clusterdeployment/strategy_test.go
> Avoid cloud ssh public key name collision

- pkg/clusterapi/aws/actuator.go
- pkg/clusterapi/aws/actuator_test.go
- pkg/clusterapi/aws/client.go
- pkg/controller/awselb/aws_elb_controller.go
- pkg/controller/awselb/aws_elb_controller_test.go
- pkg/controller/controller_utils.go
redo the parameters needed to set up an aws client (needed for other stuff i'm working on) so that it doesn't need to know about the internals of machinesetspec objects.
update controllers and tests using the aws client accordingly
> aws client setup refactor

- Makefile
- build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api-common.yaml
- build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api-development.yaml
- build/cluster-operator-ansible/playbooks/cluster-api-prep/deploy-cluster-api-production.yaml
- build/cluster-operator-ansible/playbooks/cluster-api-prep/files/cluster-operator-remote-controllers-template-dev.yaml
- build/cluster-operator-ansible/playbooks/cluster-api-prep/files/cluster-operator-remote-controllers-template.yaml
- cmd/cluster-operator-controller-manager/app/controllermanager.go
- cmd/cluster-operator-controller-manager/app/options/options.go
- contrib/examples/cluster-deployment-template.yaml
- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/clusteroperator/zz_generated.deepcopy.go
- pkg/apis/componentconfig/types.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/controller_utils.go
- pkg/controller/nodelink/node_link_controller.go
- pkg/controller/nodelink/node_link_controller_test.go
- pkg/controller/remotemachineset/remotemachineset_controller.go
- pkg/controller/remotemachineset/remotemachineset_controller_test.go
- pkg/openapi/openapi_generated.go
- applies the machine annotation to the node
- applies the desired labels/taints to the node
- now runs the new controller in a "cluster-operator-remote-controllers" deployment in the target cluster.
- NOTE: changing labels on a machineset is not reflected on pre-existing machines, let alone their nodes. Issue filed upstream to see if this is desired: https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/apis/cluster/v1alpha1/machine_types.go#L52
- NOTE: labels will not be applied to masters as they are not created in-cluster, where the controller is running today.
> Add controller to link machines to nodes and apply labels + taints.

- contrib/ansible/deploy-playbook.yml
- contrib/examples/cluster-api-controllers-template.yaml
- contrib/examples/cluster-operator-template.yaml
Currently the deployment playbook uses a `BuildConfig` to build the operator from source during deployment. This is no longer needed, because there are already pre-built images published, so this patch changes the playbook to use those pre-built images.
> Use pre-built images instead of BuildConfig

- Makefile
- build/build-image/Dockerfile
- build/cluster-operator/Dockerfile
- build/fake-machine-controller/Dockerfile
- build/fake-openshift-ansible/Dockerfile
- build/playbook-mock/Dockerfile
Removes use of debian-based images in our image builds.
Switches from ADD to the more efficient COPY instruction in existing Dockerfiles
> Use Red Hat base images

- cmd/cluster-operator-controller-manager/app/controllermanager.go
- cmd/cluster-operator-controller-manager/app/options/options.go
- contrib/ansible/create-cluster-playbook.yml
- contrib/examples/cluster-deployment-template.yaml
- pkg/ansible/generate.go
- pkg/ansible/generate_test.go
- pkg/ansible/jobgeneratorexecutor.go
- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
- pkg/apis/componentconfig/types.go
- pkg/clusterapi/aws/client.go
- pkg/clusterapi/aws/mock/client_generated.go
- pkg/controller/clusterinstall/controller.go
- pkg/controller/components/components_controller.go
- pkg/controller/controller_utils.go
- pkg/controller/registryinfra/registryinfra_controller.go
- pkg/controller/registryinfra/registryinfra_controller_test.go
- pkg/openapi/openapi_generated.go
- test/integration/controller_test.go
controller to handle setting up the necessary infra pieces so that a cluster can run with an S3-backed registry
update pkg/ansible/generate to populate the various openshift_hosted_registry* ansible variables
introduce registryinfra controller to watch for new clusters and create:
an s3 bucket
an IAM user for the cluster registry to use to talk to the s3 bucket
a kube secret holding the IAM creds to be passed to the registry
allow non-s3-backed-registry by annotating the clusterdeployment:
clusteroperator.openshift.io/s3-backed-registry: "false"
> registry infra controller

- Makefile
- build/cluster-operator-ansible/Dockerfile.v3.10
- build/cluster-operator-ansible/Dockerfile.v3.9
- contrib/ansible/deploy-devel-playbook.yml
Allows us to remove workarounds that only applied to previous versions
Introduces image based on the master branch, preparing us to provision origin 3.11
> Split cluster-operator-ansible build by version

- pkg/ansible/generate.go
Current vars file generation results in a file that looks like:
```
---
all:
vars:
...     
openshift_aws_node_groups:
- name: "{{ openshift_aws_clusterid }} infra group"
group: infra
tags:
host-type: node
sub-host-type: infra
runtime: docker
Name: "{{ openshift_aws_clusterid }}-infra"
- name: "{{ openshift_aws_clusterid }} compute group"
group: compute
tags:
host-type: node
sub-host-type: compute
runtime: docker
Name: "{{ openshift_aws_clusterid }}-compute"
openshift_release: "3.10"
oreg_url: openshift/origin-${component}:v3.10.0
```
which makes version vars not to get included under `all.vars` and ignored by ansible
> Fix indent for cluster version vars

- build/cluster-operator-ansible/Dockerfile.v3.10
The latest version of the openshift-ansible 3.10 image no longer includes git, which breaks our Dockerfile build.
> Install git in origin ansible 3.10 image

- Makefile
When running a clean images build, the build fails because a coutil binary has not yet been built when building the cluster-operator image. This pull adds the coutil binary as a dependency to fix the issue.
> Add coutil as a dependency to cluster-operator image target

- Makefile
- build/cluster-operator-ansible/Dockerfile
- build/cluster-operator-ansible/playbooks.v3_11/cluster-operator/aws/infrastructure.yml
Fixes issue introduced by a change in openshift-ansible that removes the `openshift_aws_master_group_config` variable from the openshift_aws role.
The override will only be done for the cluster-operator-ansible image that's based on master and will not affect v3.9 or v3.10 builds.
> Fix IAM role creation with openshift-ansible v3.11

- pkg/ansible/generate.go
- pkg/apis/clusteroperator/types.go
- pkg/apis/clusteroperator/v1alpha1/types.go
- pkg/apis/clusteroperator/v1alpha1/zz_generated.conversion.go
- pkg/openapi/openapi_generated.go
Adds an optional EtcdImage field to ClusterVersion. if specified, that field is passed to ansible. This allows specifying an etcd image that comes from a different registry as the rest of the openshift images.
> Add Etcd image field to ClusterVersion

- contrib/cmd/coutil/main.go
- contrib/pkg/aws_tag_deprovision/aws_tag_deprovision.go
the label-based uninstaller tool will take a key=value as the basic filtering/matching mechanism to identify and remove AWS objects matching the tag/value.
there is special handling for untagged items (IAM objects in particular) where before deleting an object the tool will identify and remove any dependent objects that could otherwise not be found with tagging.
the general flow is that goroutines for each top-level-AWS-object type are launched and will spin (with backoff) and retry until each goroutine finds no more objects to delete.
the tool retries in the face of errors calling into the AWS API, but exceptional errors (like internal data manipulation and timeouts) cause the program to exit prematurely.
> label-based uninstaller
